AWSTemplateFormatVersion: '2010-09-09'
Description: OptmiseBiddingML CommonBuilderIAM
Parameters:
  EnvType:
    Description: Environment type.
    Type: String
    AllowedValues:
      - Common
  DebugName:
    Description: DebugName
    Type: String
    Default: ""
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      Path: /
      RoleName: !Sub ${DebugName}OptimiseBiddingMLCodeBuild
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Description: Allows CodeBuild to call AWS services on your behalf.
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: EC2
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - ec2:*
                Resource: "*"
        - PolicyName: SSM
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - ssm:ListCommands
                  - ssm:ListDocumentVersions
                  - ssm:DescribeMaintenanceWindowSchedule
                  - ssm:DescribeInstancePatches
                  - ssm:ListInstanceAssociations
                  - ssm:GetParameter
                  - ssm:GetMaintenanceWindowExecutionTaskInvocation
                  - ssm:DescribeAutomationExecutions
                  - ssm:GetMaintenanceWindowTask
                  - ssm:DescribeMaintenanceWindowExecutionTaskInvocations
                  - ssm:DescribeAutomationStepExecutions
                  - ssm:DescribeParameters
                  - ssm:ListResourceDataSync
                  - ssm:ListDocuments
                  - ssm:DescribeMaintenanceWindowsForTarget
                  - ssm:ListComplianceItems
                  - ssm:GetConnectionStatus
                  - ssm:GetMaintenanceWindowExecutionTask
                  - ssm:GetOpsItem
                  - ssm:GetMaintenanceWindowExecution
                  - ssm:ListResourceComplianceSummaries
                  - ssm:GetParameters
                  - ssm:DescribeOpsItems
                  - ssm:DescribeMaintenanceWindows
                  - ssm:DescribeEffectivePatchesForPatchBaseline
                  - ssm:GetServiceSetting
                  - ssm:DescribeAssociationExecutions
                  - ssm:DescribeDocumentPermission
                  - ssm:ListCommandInvocations
                  - ssm:GetAutomationExecution
                  - ssm:DescribePatchGroups
                  - ssm:GetDefaultPatchBaseline
                  - ssm:DescribeDocument
                  - ssm:DescribeMaintenanceWindowTasks
                  - ssm:ListAssociationVersions
                  - ssm:GetPatchBaselineForPatchGroup
                  - ssm:PutConfigurePackageResult
                  - ssm:DescribePatchGroupState
                  - ssm:DescribeMaintenanceWindowExecutions
                  - ssm:GetManifest
                  - ssm:DescribeMaintenanceWindowExecutionTasks
                  - ssm:DescribeInstancePatchStates
                  - ssm:DescribeInstancePatchStatesForPatchGroup
                  - ssm:GetDocument
                  - ssm:GetInventorySchema
                  - ssm:GetParametersByPath
                  - ssm:GetMaintenanceWindow
                  - ssm:DescribeInstanceAssociationsStatus
                  - ssm:DescribeAssociationExecutionTargets
                  - ssm:GetPatchBaseline
                  - ssm:DescribeInstanceProperties
                  - ssm:ListInventoryEntries
                  - ssm:DescribeAssociation
                  - ssm:GetDeployablePatchSnapshotForInstance
                  - ssm:DescribeSessions
                  - ssm:GetParameterHistory
                  - ssm:DescribeMaintenanceWindowTargets
                  - ssm:DescribePatchBaselines
                  - ssm:DescribeEffectiveInstanceAssociations
                  - ssm:DescribeInventoryDeletions
                  - ssm:DescribePatchProperties
                  - ssm:GetInventory
                  - ssm:GetOpsSummary
                  - ssm:DescribeActivations
                  - ssm:GetCommandInvocation
                  - ssm:ListComplianceSummaries
                  - ssm:DescribeInstanceInformation
                  - ssm:ListTagsForResource
                  - ssm:DescribeDocumentParameters
                  - ssm:ListAssociations
                  - ssm:DescribeAvailablePatches
                Resource: "*"
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: PIDAdditional
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource:
                  - !Sub arn:aws:codebuild:ap-northeast-1:${AWS::AccountId}:report-group/*OptimiseBiddingML-PID-*
  CodePipelineRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      Path: /service-role/
      RoleName: !Sub ${DebugName}OptimiseBiddingMLCodePipeline
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Policies:
        - PolicyName: Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                - iam:PassRole
                Resource: "*"
                Effect: Allow
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - cloudformation.amazonaws.com
                      - elasticbeanstalk.amazonaws.com
                      - ec2.amazonaws.com
                      - ecs-tasks.amazonaws.com
              - Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetRepository
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                Resource: "*"
                Effect: Allow
              - Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplication
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                Resource: "*"
                Effect: Allow
              - Action:
                  - codestar-connections:UseConnection
                Resource: "*"
                Effect: Allow
              - Action:
                  - elasticbeanstalk:*
                  - ec2:*
                  - elasticloadbalancing:*
                  - autoscaling:*
                  - cloudwatch:*
                  - s3:*
                  - sns:*
                  - cloudformation:*
                  - rds:*
                  - sqs:*
                  - ecs:*
                Resource: "*"
                Effect: Allow
              - Action:
                  - lambda:InvokeFunction
                  - lambda:ListFunctions
                Resource: "*"
                Effect: Allow
              - Action:
                  - opsworks:CreateDeployment
                  - opsworks:DescribeApps
                  - opsworks:DescribeCommands
                  - opsworks:DescribeDeployments
                  - opsworks:DescribeInstances
                  - opsworks:DescribeStacks
                  - opsworks:UpdateApp
                  - opsworks:UpdateStack
                Resource: "*"
                Effect: Allow
              - Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                Resource: "*"
                Effect: Allow
              - Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuildBatches
                  - codebuild:StartBuildBatch
                Resource: "*"
                Effect: Allow
              - Effect: Allow
                Action:
                  - devicefarm:ListProjects
                  - devicefarm:ListDevicePools
                  - devicefarm:GetRun
                  - devicefarm:GetUpload
                  - devicefarm:CreateUpload
                  - devicefarm:ScheduleRun
                Resource: "*"
              - Effect: Allow
                Action:
                  - servicecatalog:ListProvisioningArtifacts
                  - servicecatalog:CreateProvisioningArtifact
                  - servicecatalog:DescribeProvisioningArtifact
                  - servicecatalog:DeleteProvisioningArtifact
                  - servicecatalog:UpdateProduct
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:DescribeImages
                Resource: "*"
              - Effect: Allow
                Action:
                  - states:DescribeExecution
                  - states:DescribeStateMachine
                  - states:StartExecution
                Resource: "*"
              - Effect: Allow
                Action:
                  - appconfig:StartDeployment
                  - appconfig:StopDeployment
                  - appconfig:GetDeployment
                Resource: "*"
