version: '3'
services:
  cdk:
    platform: linux/x86_64
    build:
      context: .
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    tty: true
    entrypoint: "sh"
