version: '3'
services:
  it:
    build: .
    privileged: true
    tty: true
    volumes:
      - ../:/work
      - /var/run/docker.sock:/var/run/docker.sock
    platform: linux/amd64
    entrypoint: /bin/bash
    working_dir: /work/integration_test
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
      - MINIO_URL=http://minio:9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - NETWORK_NAME=integration_test_default
  minio:
    build:
      context: ../minio
    ports:
      - 9090:9000
      - 9091:9001
    volumes:
      - ../minio/data:/data
      - ../minio/config:/root/.minio
      - ../minio/scripts:/scripts
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_WEB_PORT=9001
      - MINIO_DATA_DIR=/data
    entrypoint: ""
    command: bash /scripts/start_minio.sh
