FILLNA_COLUMNS = {
    'impressions',
    'clicks',
    'costs',
    'conversions',
    'sales',
    'p_error',
    'q_error',
    'p_sum_error',
    'q_sum_error',
}

PREPROCESS_COLUMNS = [
    'portfolio_id',
    'advertising_account_id',
    'ad_type',
    'ad_id',
    'date',
    'impressions',
    'clicks',
    'conversions',
    'sales',
    'costs',
    'bidding_price',
    'cvr',
    'rpc',
    'cpc',
    'purpose',
    'mode',
    'target_kpi',
    'target_cost',
    'base_target_cost',
    'target_kpi_value',
    'is_enabled_bidding_auto_adjustment',
    'p', 'q',
    'p_kp', 'p_ki', 'p_kd',
    'p_error', 'p_sum_error',
    'q_kp', 'q_ki', 'q_kd',
    'q_error', 'q_sum_error',
    'not_ml_applied_days',
    'yesterday_target_kpi',
    'unit_ex_observed_C',
]

OUTPUT_COLUMNS = [
    'advertising_account_id',
    'portfolio_id',
    'date',
    'target_cost',
    'base_target_cost',
    'p',
    'q',
    'pre_reupdate_p',
    'pre_reupdate_q',
    'p_kp',
    'p_ki',
    'p_kd',
    'p_error',
    'p_sum_error',
    'q_kp',
    'q_ki',
    'q_kd',
    'q_error',
    'q_sum_error',
    'origin_p',
    'origin_q',
    'error',
    'is_updated',
    'is_pid_initialized',
    'is_skip_pid_calc_state',
    'obs_kpi',
    'valid_ads_num',
]

ML_LOOKUP_DAYS = 3
